"""
Flask test runner — synchronous execution.

POST /run-tests  → runs pytest + AI analysis, returns full JSON result (blocks until done)
GET  /health     → liveness probe
GET  /download-report → download the most recently generated PDF report
"""

import json
import logging
import os
import re
import subprocess
import sys
import threading
import traceback
import uuid
from datetime import datetime, timezone
from pathlib import Path

from flask import Flask, jsonify, make_response, request, send_file

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from service.pdf_report_generator import generate_pdf, generate_pipeline_pdf

app = Flask(__name__)

PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_DIR = PROJECT_ROOT / "output"
REPORTS_DIR = OUTPUT_DIR / "reports"
LOGS_DIR = OUTPUT_DIR / "logs"

# ---------------------------------------------------------------------------
# Ensure output directories exist at import time (not just under __main__)
# so anything that imports this module — tests, MCP servers, etc. — never
# hits a FileNotFoundError before the first request.
# ---------------------------------------------------------------------------
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
LOGS_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# File logger — writes to output/logs/flask.log
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOGS_DIR / "flask.log", encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Shared-secret guard
# ---------------------------------------------------------------------------
_FLASK_SECRET = os.environ.get("FLASK_SECRET", "")


@app.before_request
def _require_secret():
    """Reject requests that don't carry the correct X-Secret header.

    If FLASK_SECRET is not set the check is skipped — local dev works
    without configuration.  In production set FLASK_SECRET and pass the
    same value from n8n via an X-Secret header.
    """
    if not _FLASK_SECRET:
        return
    if request.headers.get("X-Secret") != _FLASK_SECRET:
        return make_response(jsonify({"error": "Unauthorized"}), 401)


# ---------------------------------------------------------------------------
# Latest-report store — lets /download-report work after any run
# ---------------------------------------------------------------------------
_latest_pdf: dict | None = None
_latest_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Route: POST /run-tests  (synchronous — blocks until tests + analysis done)
# ---------------------------------------------------------------------------


@app.route("/run-tests", methods=["POST"])
def run_tests():
    """
    Run the full pytest suite and return results immediately.

    The endpoint blocks until:
      1. pytest finishes
      2. the result JSON is parsed
      3. ReportAnalysisAgent enriches every failure with classification,
         recommendation, root-cause, and AI analysis
      4. a PDF report is generated

    Response 200:
        {
            "run_id":           "<uuid>",
            "execution_status": "PASSED" | "FAILED",
            "summary":          { total, passed, failed, duration },
            "all_tests":        [...],
            "failed_tests":     [...],   # each has classification, recommendation, ai_analysis
            "root_cause":       "...",
            "email_message":    "...",
            "pdf_report":       "output/reports/<run_id>/QA_Execution_Report.pdf"
        }

    Response 500 on internal error.
    """
    global _latest_pdf

    run_id = str(uuid.uuid4())
    run_dir = REPORTS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    result_file = run_dir / "result.json"
    html_report = run_dir / "test_report.html"

    log.info("[run:%s] Starting pytest…", run_id)
    started_at = datetime.now(timezone.utc).isoformat()

    try:
        proc = subprocess.run(
            [
                sys.executable,
                "-m",
                "pytest",
                "-v",
                "--json-report",
                f"--json-report-file={result_file}",
                f"--html={html_report}",
                "--self-contained-html",
            ],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        log.info("[run:%s] pytest exit code: %s", run_id, proc.returncode)

        if not result_file.exists():
            raise RuntimeError("result.json was not generated by pytest")

        with open(result_file, encoding="utf-8") as fh:
            pytest_data = json.load(fh)

        # ── Run ReportAnalysisAgent for enriched per-failure analysis ─────
        agent_lookup: dict = {}
        root_cause: str = ""
        try:
            from agents.analysis.report_analysis_agent import ReportAnalysisAgent

            agent = ReportAnalysisAgent(str(result_file))
            full_analysis = agent.generate_analysis()
            root_cause = full_analysis.get("root_cause", "")
            for failure in full_analysis.get("failures", []):
                agent_lookup[failure["test"]] = failure
        except Exception as agent_err:
            log.warning("[run:%s] ReportAnalysisAgent skipped: %s", run_id, agent_err)

        # ── Summary ──────────────────────────────────────────────────────
        raw = pytest_data.get("summary", {})
        summary = {
            "total": raw.get("total", 0),
            "passed": raw.get("passed", 0),
            "failed": raw.get("failed", 0),
            "duration": round(pytest_data.get("duration", 0), 2),
        }

        # ── Per-test breakdown ───────────────────────────────────────────
        failed_tests: list = []
        all_tests: list = []

        for item in pytest_data.get("tests", []):
            node_id = item.get("nodeid", "")
            test_fn = node_id.split("::")[-1]
            name = test_fn.replace("test_", "").replace("_", " ").title()
            outcome = item.get("outcome", "unknown").upper()

            # Screenshots are now saved to output/screenshots/
            screenshot_path = f"output/screenshots/{test_fn}.png"
            screenshot_exists = (PROJECT_ROOT / screenshot_path).exists()

            all_tests.append(
                {
                    "name": name,
                    "status": outcome,
                    "screenshot": screenshot_path if screenshot_exists else None,
                }
            )

            if outcome == "FAILED":
                call = item.get("call", {})
                longrepr = str(call.get("longrepr", ""))
                crash = call.get("crash", {})

                crash_message = crash.get("message", "").strip()
                reason = crash_message.split("\n")[0].strip() or "Test failed"

                failing_step = None
                m = re.search(
                    r'@(given|when|then)\s*\(\s*["\'](.+?)["\']\s*\)',
                    longrepr,
                    re.IGNORECASE,
                )
                if m:
                    failing_step = f"{m.group(1).capitalize()}: {m.group(2)}"

                execution_log = [e.get("msg", "") for e in call.get("log", []) if e.get("msg")]

                # Pull enriched analysis from ReportAnalysisAgent
                enriched = agent_lookup.get(node_id, {})

                failed_tests.append(
                    {
                        "name": name,
                        "status": outcome,
                        "failing_step": failing_step,
                        "crash_message": crash_message,
                        "reason": reason,
                        "execution_log": execution_log,
                        "jira_summary": f"Automation Failure - {name}",
                        "screenshot": screenshot_path if screenshot_exists else None,
                        "classification": enriched.get(
                            "classification", "Unknown — Requires Investigation"
                        ),
                        "recommendation": enriched.get(
                            "recommendation", "Review assertion failure and application behaviour."
                        ),
                        "ai_analysis": enriched.get("ai_analysis", "AI analysis unavailable."),
                    }
                )

        passed = proc.returncode == 0
        email_message = (
            f"QA Automation execution completed successfully. All {summary['total']} tests passed."
            if passed
            else f"QA Automation execution completed with {summary['failed']} failed test(s)."
        )

        payload = {
            "run_id": run_id,
            "execution_status": "PASSED" if passed else "FAILED",
            "started_at": started_at,
            "finished_at": datetime.now(timezone.utc).isoformat(),
            "email_message": email_message,
            "root_cause": root_cause,
            "summary": summary,
            "failed_tests": failed_tests,
            "all_tests": all_tests,
            "html_report": str(html_report.relative_to(PROJECT_ROOT)),
        }

        # ── PDF ──────────────────────────────────────────────────────────
        pdf_path = run_dir / "QA_Execution_Report.pdf"
        try:
            generate_pdf(payload, pdf_path, project_root=PROJECT_ROOT)
            payload["pdf_report"] = str(pdf_path.relative_to(PROJECT_ROOT))
            log.info("[run:%s] PDF: %s", run_id, pdf_path)
            with _latest_lock:
                _latest_pdf = {"path": pdf_path, "run_id": run_id}
        except Exception as pdf_err:
            log.warning("[run:%s] PDF failed: %s", run_id, pdf_err)
            payload["pdf_report"] = None

        log.info("[run:%s] Done — %s", run_id, payload["execution_status"])
        return jsonify(payload), 200

    except Exception as exc:
        tb = traceback.format_exc()
        log.error("[run:%s] ERROR:\n%s", run_id, tb)
        return make_response(
            jsonify({"error": str(exc), "traceback": tb, "run_id": run_id}),
            500,
        )


# ---------------------------------------------------------------------------
# Jira → Playwright pipeline job store
# ---------------------------------------------------------------------------
_pipeline_job: dict | None = None
_pipeline_lock = threading.Lock()


def _run_pipeline_in_background(job_id: str) -> None:
    """Run the 3-stage Jira→Playwright pipeline in a background thread."""
    global _latest_pipeline_pdf  # must be declared global before assignment

    import asyncio

    from agents.pipelines.jira_playwright import run as run_pipeline

    log.info("[pipeline:%s] Starting…", job_id)
    try:
        results = asyncio.run(run_pipeline())
        finished_at = datetime.now(timezone.utc).isoformat()

        # Generate PDF
        pdf_path_str: str | None = None
        try:
            run_dir = REPORTS_DIR / job_id
            run_dir.mkdir(parents=True, exist_ok=True)
            pdf_file = run_dir / "Jira_Pipeline_Report.pdf"
            pipeline_data = {
                "job_id": job_id,
                "status": "complete",
                "started_at": _pipeline_job.get("started_at", ""),  # type: ignore[union-attr]
                "finished_at": finished_at,
                "bug_analysis": results.get("bug_analysis", ""),
                "test_execution": results.get("test_execution", ""),
                "jira_update": results.get("jira_update", ""),
            }
            generate_pipeline_pdf(pipeline_data, output_path=pdf_file)
            pdf_path_str = str(pdf_file.relative_to(PROJECT_ROOT))
            with _pipeline_pdf_lock:
                _latest_pipeline_pdf = {"path": pdf_file, "run_id": job_id}
            log.info("[pipeline:%s] PDF: %s", job_id, pdf_file)
        except Exception as pdf_err:
            log.warning("[pipeline:%s] PDF generation failed: %s", job_id, pdf_err)

        with _pipeline_lock:
            _pipeline_job.update(  # type: ignore[union-attr]
                {
                    "status": "complete",
                    "finished_at": finished_at,
                    "bug_analysis": results.get("bug_analysis", ""),
                    "test_execution": results.get("test_execution", ""),
                    "jira_update": results.get("jira_update", ""),
                    "pdf_report": pdf_path_str,
                }
            )
        log.info("[pipeline:%s] Complete.", job_id)
    except Exception as exc:
        tb = traceback.format_exc()
        log.error("[pipeline:%s] ERROR:\n%s", job_id, tb)
        with _pipeline_lock:
            _pipeline_job.update(
                {  # type: ignore[union-attr]
                    "status": "error",
                    "finished_at": datetime.now(timezone.utc).isoformat(),
                    "error": str(exc),
                }
            )


# ---------------------------------------------------------------------------
# Route: POST /run-jira-pipeline  (async background — returns 202 immediately)
# ---------------------------------------------------------------------------


@app.route("/run-jira-pipeline", methods=["POST"])
def run_jira_pipeline():
    """Start the Jira → Playwright → Jira update pipeline in the background.

    Response 202 (started):
        { "job_id": "<uuid>", "status": "running" }

    Response 409 (already running):
        { "error": "Pipeline already running", "job_id": "<uuid>" }
    """
    global _pipeline_job

    with _pipeline_lock:
        if _pipeline_job and _pipeline_job.get("status") == "running":
            return jsonify(
                {"error": "Pipeline already running", "job_id": _pipeline_job["job_id"]}
            ), 409

        job_id = str(uuid.uuid4())
        _pipeline_job = {
            "job_id": job_id,
            "status": "running",
            "started_at": datetime.now(timezone.utc).isoformat(),
            "finished_at": None,
            "bug_analysis": None,
            "test_execution": None,
            "jira_update": None,
            "error": None,
        }

    thread = threading.Thread(
        target=_run_pipeline_in_background,
        args=(job_id,),
        daemon=True,
        name=f"jira-pipeline-{job_id[:8]}",
    )
    thread.start()
    log.info("[pipeline:%s] Background thread started.", job_id)
    return jsonify({"job_id": job_id, "status": "running"}), 202


# ---------------------------------------------------------------------------
# Route: GET /pipeline-status  (poll for pipeline results)
# ---------------------------------------------------------------------------


@app.route("/pipeline-status", methods=["GET"])
def pipeline_status():
    """Poll the status of the most recent Jira pipeline run.

    Response 200 while running:
        { "job_id": "...", "status": "running", "started_at": "..." }

    Response 200 when complete:
        {
            "job_id":         "...",
            "status":         "complete",
            "started_at":     "...",
            "finished_at":    "...",
            "bug_analysis":   "...",   # Stage 1 output
            "test_execution": "...",   # Stage 2 output
            "jira_update":    "..."    # Stage 3 output
        }

    Response 200 on error:
        { "job_id": "...", "status": "error", "error": "..." }

    Response 404 if no pipeline has been triggered yet.
    """
    with _pipeline_lock:
        job = dict(_pipeline_job) if _pipeline_job else None

    if job is None:
        return make_response(
            jsonify({"error": "No pipeline run yet. POST /run-jira-pipeline first."}), 404
        )

    return jsonify(job), 200


# ---------------------------------------------------------------------------
# Route: GET /health
# ---------------------------------------------------------------------------


@app.route("/health", methods=["GET"])
def health():
    """Liveness probe."""
    return jsonify({"status": "ok"}), 200


# ---------------------------------------------------------------------------
# Latest pipeline PDF store (separate from pytest PDF)
# ---------------------------------------------------------------------------
_latest_pipeline_pdf: dict | None = None
_pipeline_pdf_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Route: GET /download-report  (pytest regression report)
# ---------------------------------------------------------------------------


@app.route("/download-report", methods=["GET"])
def download_latest_report():
    """Download the most recently generated PDF (pytest report OR pipeline report).

    Serves whichever PDF was generated most recently.  This lets both the
    QA Test Execution Orchestrator (v3) and the Jira Pipeline (v1) n8n
    workflows use the same endpoint without re-importing the workflow JSON.
    """
    with _latest_lock:
        pytest_pdf = _latest_pdf
    with _pipeline_pdf_lock:
        pipeline_pdf = _latest_pipeline_pdf

    # Pick the most recently created PDF
    candidates = [p for p in [pytest_pdf, pipeline_pdf] if p and p["path"].exists()]
    if not candidates:
        return make_response(
            jsonify({"error": "No report available yet. Run /run-tests or /run-jira-pipeline first."}),
            404,
        )

    # Sort by modification time of the PDF file; serve the newest
    latest = max(candidates, key=lambda p: p["path"].stat().st_mtime)

    return send_file(
        latest["path"],
        as_attachment=True,
        download_name=latest["path"].name,
    )


# ---------------------------------------------------------------------------
# Route: GET /download-pipeline-pdf  (Jira pipeline report)
# ---------------------------------------------------------------------------


@app.route("/download-pipeline-pdf", methods=["GET"])
def download_pipeline_pdf():
    """Download the PDF from the most recent Jira pipeline run."""
    with _pipeline_pdf_lock:
        latest = _latest_pipeline_pdf

    if latest is None or not latest["path"].exists():
        return make_response(
            jsonify({"error": "No pipeline PDF available yet. POST /run-jira-pipeline first."}),
            404,
        )

    return send_file(
        latest["path"],
        as_attachment=True,
        download_name="Jira_Pipeline_Report.pdf",
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    port = int(os.environ.get("FLASK_PORT", 5001))
    app.run(
        host="0.0.0.0",
        port=port,
        debug=False,
        use_reloader=False,
    )
