"""
Flask test runner — synchronous execution.

POST /run-tests  → runs pytest, AI analysis, returns full JSON result (blocks until done)
GET  /health     → liveness probe
GET  /download-report → download the most recently generated PDF report
"""

import json
import logging
import os
import re
import subprocess
import sys
import threading
import traceback
import uuid
from datetime import datetime, timezone
from pathlib import Path

from flask import Flask, jsonify, make_response, request, send_file

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from service.pdf_report_generator import generate_pdf

app = Flask(__name__)

PROJECT_ROOT = Path(__file__).parent.parent
OUTPUT_DIR   = PROJECT_ROOT / "output"
REPORTS_DIR  = OUTPUT_DIR / "reports"
LOGS_DIR     = OUTPUT_DIR / "logs"

# ---------------------------------------------------------------------------
# File logger — writes to logs/flask.log
# ---------------------------------------------------------------------------
LOGS_DIR.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOGS_DIR / "flask.log", encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Shared-secret guard
# ---------------------------------------------------------------------------
_FLASK_SECRET = os.environ.get("FLASK_SECRET", "")


@app.before_request
def _require_secret():
    """Reject requests that don't carry the correct X-Secret header.

    If FLASK_SECRET is not set the check is skipped so local dev/test
    works without configuration.  In production set FLASK_SECRET and
    pass the same value from n8n via an X-Secret header.
    """
    if not _FLASK_SECRET:
        return
    if request.headers.get("X-Secret") != _FLASK_SECRET:
        return make_response(jsonify({"error": "Unauthorized"}), 401)


# ---------------------------------------------------------------------------
# Latest-report store — lets /download-report work after any run
# ---------------------------------------------------------------------------
_latest_pdf: dict | None = None   # {"path": Path, "run_id": str}
_latest_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Route: POST /run-tests  (synchronous — blocks until tests + analysis done)
# ---------------------------------------------------------------------------

@app.route("/run-tests", methods=["POST"])
def run_tests():
    """
    Run the full pytest suite and return results immediately.

    The endpoint blocks until:
      1. pytest finishes
      2. the result JSON is parsed
      3. a PDF report is generated
      4. AI failure analysis is applied to every failed test

    Response 200:
        {
            "run_id":           "<uuid>",
            "execution_status": "PASSED" | "FAILED",
            "summary":          { total, passed, failed, duration },
            "all_tests":        [...],
            "failed_tests":     [...],   # each has "ai_analysis" when failed
            "email_message":    "...",
            "pdf_report":       "reports/<run_id>/QA_Execution_Report.pdf"
        }

    Response 500 on internal error.
    """
    global _latest_pdf

    run_id  = str(uuid.uuid4())
    run_dir = REPORTS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    result_file = run_dir / "result.json"
    html_report = run_dir / "test_report.html"

    log.info("[run:%s] Starting pytest…", run_id)
    started_at = datetime.now(timezone.utc).isoformat()

    try:
        proc = subprocess.run(
            [
                sys.executable, "-m", "pytest", "-v",
                "--json-report",
                f"--json-report-file={result_file}",
                f"--html={html_report}",
                "--self-contained-html",
            ],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        log.info("[run:%s] pytest exit code: %s", run_id, proc.returncode)

        if not result_file.exists():
            raise RuntimeError("result.json was not generated by pytest")

        with open(result_file, encoding="utf-8") as fh:
            pytest_data = json.load(fh)

        # ── Summary ──────────────────────────────────────────────────────
        raw = pytest_data.get("summary", {})
        summary = {
            "total":    raw.get("total",  0),
            "passed":   raw.get("passed", 0),
            "failed":   raw.get("failed", 0),
            "duration": round(pytest_data.get("duration", 0), 2),
        }

        # ── Per-test breakdown ───────────────────────────────────────────
        failed_tests: list = []
        all_tests:    list = []

        for item in pytest_data.get("tests", []):
            node_id = item.get("nodeid", "")
            test_fn = node_id.split("::")[-1]
            name    = test_fn.replace("test_", "").replace("_", " ").title()
            outcome = item.get("outcome", "unknown").upper()

            screenshot_path   = f"screenshots/{test_fn}.png"
            screenshot_exists = (PROJECT_ROOT / screenshot_path).exists()

            all_tests.append({
                "name":       name,
                "status":     outcome,
                "screenshot": screenshot_path if screenshot_exists else None,
            })

            if outcome == "FAILED":
                call     = item.get("call", {})
                longrepr = str(call.get("longrepr", ""))
                crash    = call.get("crash", {})

                crash_message = crash.get("message", "").strip()
                reason = crash_message.split("\n")[0].strip() or "Test failed"

                failing_step = None
                m = re.search(
                    r'@(given|when|then)\s*\(\s*["\'](.+?)["\']\s*\)',
                    longrepr, re.IGNORECASE,
                )
                if m:
                    failing_step = f"{m.group(1).capitalize()}: {m.group(2)}"

                execution_log = [
                    e.get("msg", "")
                    for e in call.get("log", [])
                    if e.get("msg")
                ]

                # ── AI analysis ──────────────────────────────────────────
                ai_analysis = _run_ai_analysis(
                    node_id, crash_message, execution_log
                )

                failed_tests.append({
                    "name":          name,
                    "status":        outcome,
                    "failing_step":  failing_step,
                    "crash_message": crash_message,
                    "reason":        reason,
                    "execution_log": execution_log,
                    "jira_summary":  f"Automation Failure - {name}",
                    "screenshot":    screenshot_path if screenshot_exists else None,
                    "ai_analysis":   ai_analysis,
                })

        passed = proc.returncode == 0
        if passed:
            email_message = (
                f"QA Automation execution completed successfully. "
                f"All {summary['total']} tests passed."
            )
        else:
            email_message = (
                f"QA Automation execution completed with "
                f"{summary['failed']} failed test(s)."
            )

        payload = {
            "run_id":           run_id,
            "execution_status": "PASSED" if passed else "FAILED",
            "started_at":       started_at,
            "finished_at":      datetime.now(timezone.utc).isoformat(),
            "email_message":    email_message,
            "summary":          summary,
            "failed_tests":     failed_tests,
            "all_tests":        all_tests,
            "html_report":      str(html_report.relative_to(PROJECT_ROOT)),
        }

        # ── PDF ──────────────────────────────────────────────────────────
        pdf_path = run_dir / "QA_Execution_Report.pdf"
        try:
            generate_pdf(payload, pdf_path)
            payload["pdf_report"] = str(pdf_path.relative_to(PROJECT_ROOT))
            log.info("[run:%s] PDF: %s", run_id, pdf_path)
            with _latest_lock:
                _latest_pdf = {"path": pdf_path, "run_id": run_id}
        except Exception as pdf_err:
            log.warning("[run:%s] PDF failed: %s", run_id, pdf_err)
            payload["pdf_report"] = None

        log.info("[run:%s] Done — %s", run_id, payload["execution_status"])
        return jsonify(payload), 200

    except Exception as exc:
        tb = traceback.format_exc()
        log.error("[run:%s] ERROR:\n%s", run_id, tb)
        return make_response(
            jsonify({"error": str(exc), "traceback": tb, "run_id": run_id}),
            500,
        )


def _run_ai_analysis(test_id: str, error: str, logs: list) -> str:
    """Call ReportAnalysisAgent's AI layer for a single failure.

    Imports lazily so the Flask service starts even if the agents package
    has optional dependencies missing.
    """
    try:
        from ai.ai_failure_agent import AIFailureAgent
        agent = AIFailureAgent()
        return agent.analyse({
            "test":  test_id,
            "error": error,
            "logs":  logs,
        })
    except Exception as exc:
        log.warning("AI analysis skipped: %s", exc)
        return "AI analysis unavailable."


# ---------------------------------------------------------------------------
# Route: GET /health
# ---------------------------------------------------------------------------

@app.route("/health", methods=["GET"])
def health():
    """Liveness probe."""
    return jsonify({"status": "ok"}), 200


# ---------------------------------------------------------------------------
# Route: GET /download-report  (backwards compat)
# ---------------------------------------------------------------------------

@app.route("/download-report", methods=["GET"])
def download_latest_report():
    """Download the PDF from the most recent completed run."""
    with _latest_lock:
        latest = _latest_pdf

    if latest is None or not latest["path"].exists():
        return make_response(
            jsonify({"error": "No report available yet. Run the tests first."}),
            404,
        )

    return send_file(
        latest["path"],
        as_attachment=True,
        download_name="QA_Execution_Report.pdf",
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    port = int(os.environ.get("FLASK_PORT", 5001))
    app.run(
        host="0.0.0.0",
        port=port,
        debug=False,
        use_reloader=False,
    )
